list of orderstatuses
TBD54566975/tbdex pull request #351
Opened 2024-07-11 19:11 UTC by jiyoontbd

2024-07-11 21:46 UTC, angiejones requested changes

2024-07-11 21:46 UTC, angiejones commented on hosted/json-schemas/orderstatus.schema.json
> +      "enum": [
missing `PAYIN_EXPIRED`

2024-07-11 23:32 UTC, jiyoontbd commented on hosted/json-schemas/orderstatus.schema.json
> +      "enum": [
thanks angie! https://github.com/TBD54566975/tbdex/pull/351/commits/2b3c594a5acd31db71bc4e5cda75f01bef62d6af

2024-07-11 23:45 UTC, michaelneale commented
looks good - hard to know if missing some obvious gap, are there any external references that we can point to that show this covering things or is this more as we have discovered so far?

2024-07-12 03:11 UTC, jiyoontbd commented
> looks good - hard to know if missing some obvious gap, are there any external references that we can point to that show this covering things or is this more as we have discovered so far?

@michaelneale this is more of what we've discovered so far from internal testing. of course super open to adding or removing from the enum list as we keep building with tbdex. :)

2024-07-12 14:48 UTC, angiejones approved these changes

2024-07-12 17:53 UTC, nitro-neal approved these changes

2024-07-13 01:41 UTC, michaelneale commented
@jiyoontbd SGTM - I am guessing its not too dramatic to remove later

2024-07-13 02:59 UTC, mistermoe approved these changes
Awesome work @jiyoontbd

2024-07-13 06:19 UTC, merged

2024-07-14 18:51 UTC, KendallWeihe commented
> Awesome work @jiyoontbd

Seconded!